version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    command: >
      sh -c 'if [ -n "$REDIS_PASSWORD" ]; then
      exec redis-server --save 60 1 --loglevel warning --requirepass "$REDIS_PASSWORD";
      else
      exec redis-server --save 60 1 --loglevel warning;
      fi'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "if [ -n \"$REDIS_PASSWORD\" ]; then redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG; else redis-cli ping | grep PONG; fi",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      target: final
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_prod_data:
