# Generated by Django 4.2.30 on 2026-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_printshop_logo_alter_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='captured_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='merchant_transaction_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='phonepe_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
