# Generated by Django 4.2.30 on 2026-04-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_payment_phonepe_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printshop',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
